# Preface {.unnumbered}

> "[O]f all the several ways of beginning a book which are now in practice throughout the known world, I am confident my own way of doing it is the best—I'm sure it is the most religious—for I begin with writing the first sentence—and trusting to Almighty God for the second." \
> --- Laurence Sterne, in "The Life and Opinions of Tristram Shandy, Gentleman"

Welcome!

This is the first draft of **"Topological data analysis with Julia"**.

The knowledge of Topological Data Analysis (TDA, for short) is spread across papers, books, and software documentation. My aim here is to bring the mathematical ideas and runnable Julia examples into one conversation. Code lets us test what we think we have understood.

In this book, we will outline the main methods used to analyse data with topology and work through some non-trivial examples. Besides, it is a healthy way I found to practice Julia and study TDA again.

The readers who are afraid of Mathematics are urged to at least understand the intuitive notions of the definitions and results presented here. This is why I will give many informal descriptions of the ideas and objects before formalising them. Keep in mind, however, that Mathematics is the language that best describes abstractions and the use of logic, and **you can only learn a language by using it**. For those who love math, I hope the "intuitive notions" won't seem too boring.

This book will teach the basics of topology and data analysis needed to understand TDA; unfortunately, **we will not teach you Julia** directly. For that, there are many excellent resources. See, for example:

- [Think Julia](https://benlauwens.github.io/ThinkJulia.jl/latest/book.html)
- [Julia for Optimization and Learning](https://juliateachingctu.github.io/Julia-for-Optimization-and-Learning/dev/)
- [Data Science in Julia for Hackers](https://datasciencejuliahackers.com/)

You can, however, learn something from the code examples and modify them to your needs.
